version: '3'

services:
  seaweedfs:
    image: chrislusf/seaweedfs:3.67
    container_name: seaweedfs
    ports:
      - "9000:9000"
    command: |
        server -s3 -dir="/mnt/data" -s3.config=/etc/s3/s3.conf -s3.port 9000
        -ip.bind=0.0.0.0 -master.volumePreallocate 
        -volume.fileSizeLimitMB 4096 -volume.index leveldb -volume.index.leveldbTimeout 1 
        -filer.exposeDirectoryData false
    volumes:
      - ./data:/mnt/data
      - ./seaweedfs:/etc/seaweedfs
