version: '2.3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.24
    ports:
      - 6831:6831/udp
      - 16686:16686
    environment:
      - "SPAN_STORAGE_TYPE=badger"
      - "BADGER_EPHEMERAL=false"
      - "BADGER_DIRECTORY_VALUE=/badger/data"
      - "BADGER_DIRECTORY_KEY=/badger/key"
      - "BADGER_SPAN_STORE_TTL=168h0m0s"
    volumes:
      - ./badger:/badger
    logging:
      options:
        max-size: "50m"
