server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  # - job_name: docker
  #   # Describes how to use the Docker daemon API to discover containers running on the same host as Promtail.
  #   docker_sd_configs:
  #     - host: "unix:///var/run/docker.sock"
  #       refresh_interval: 60s
  #   relabel_configs:
  #     - source_labels: ['__meta_docker_container_name']
  #       regex: '/(.*)'
  #       target_label: 'container'
  - job_name: containers
    static_configs:
    - targets:
      - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/**/*.log
