# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 1m
  scrape_timeout: 15s
  evaluation_interval: 1m

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: "server"
    metrics_path: /
    scheme: http
    static_configs:
      - targets: 
        - 172.17.0.1:8080

