# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 1m
  scrape_timeout: 15s
  evaluation_interval: 1m

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: "cadvisor"
    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: "A"
        port: 8080
  
  - job_name: 'swarm-nodes-metrics'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'gpu-nodes-metrics'
    dns_sd_configs:
    - names:
      - 'tasks.dcgm-exporter'
      type: 'A'
      port: 9400

  - job_name: 'db-pg-metrics'
    dns_sd_configs:
    - names:
      - 'tasks.postgres-exporter'
      type: 'A'
      port: 9187

  - job_name: "server"
    metrics_path: /
    scheme: http
    static_configs:
      - targets: 
        - 172.17.0.1:8080

