#!/bin/bash

# nginx Path
NGINX_CONFIG=/etc/nginx/sites-available/default

# modify nginx config
cp /defaults/default.conf ${NGINX_CONFIG}
if [ ! -z ${DISABLE_IPV6+x} ]; then
  sed -i '/listen \[::\]/d' ${NGINX_CONFIG}
fi
