version: '3'

services:
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
    container_name: nginx
    ports:
      - "8080:8080"
      - "50051:50051"